# generated by Claude Opus
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import argparse
import copy
import json
import os
from collections import Counter
from datetime import datetime

import torch
from dataset.GraphDataset import (
    GraphDatasetMeccano,
    feature_collate_fn,
)
from dataset.meccano_aux import (
    resolve_meccano_global_root,
    resolve_meccano_split_root,
    return_meccano_train_val_test_samples,
)
from modeling.LSTM import GraphLSTM
from torch.utils.data import DataLoader, WeightedRandomSampler
from tqdm import tqdm
from train.evaluate import (
    build_loss_fn,
    compute_class_weights,
    evaluate,
    store_model,
)
from train.train import do_epoch


DEFAULT_STUDY_CONFIG = {
    "study_name": "meccano_graph_lstm_hpo",
    "direction": "maximize",
    "storage": "sqlite:///meccano_graph_lstm_hpo.db",
    "load_if_exists": True,
    "n_trials": 50,
    "sampler": {
        "name": "TPESampler",
        "seed": 42,
    },
    "pruner": {
        "name": "MedianPruner",
        "n_startup_trials": 5,
        "n_warmup_steps": 3,
    },
}

DEFAULT_OBJECTIVE_CONFIG = {
    "metric": "top5",
    "run_test": False,
}


def require_optuna():
    import optuna
    return optuna


def build_train_sampler(dataset, activity_to_idx, sampler_cfg):
    if not sampler_cfg or sampler_cfg.get("name") in {None, "none"}:
        return None
    if sampler_cfg.get("name") != "balanced":
        raise ValueError(f"Unsupported sampler: {sampler_cfg.get('name')}")

    labels = [
        activity_to_idx[label_str] for _, _, label_str, _, _ in dataset.sample_index
    ]
    counts = Counter(labels)
    power = float(sampler_cfg.get("power", 1.0))
    weights = torch.tensor(
        [1.0 / (counts[label] ** power) for label in labels],
        dtype=torch.double,
    )
    num_samples = int(sampler_cfg.get("num_samples", len(weights)))
    replacement = bool(sampler_cfg.get("replacement", True))
    return WeightedRandomSampler(
        weights, num_samples=num_samples, replacement=replacement
    )


def load_best_checkpoint_if_available(model, save_path, metric="acc", device="cpu"):
    prefix = f"best_model_{metric}_epoch_"
    candidates = [
        file_name
        for file_name in os.listdir(save_path)
        if file_name.startswith(prefix) and file_name.endswith(".pt")
    ]
    if not candidates:
        return None

    def _epoch_from_name(file_name):
        epoch_str = file_name[len(prefix) : -3]
        return int(epoch_str)

    best_file = max(candidates, key=_epoch_from_name)
    checkpoint_path = os.path.join(save_path, best_file)
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint["model_state_dict"])
    return checkpoint_path


def evaluate_checkpoint(
    model,
    save_path,
    metric,
    test_loader,
    test_dataset,
    device,
    fallback_message,
):
    checkpoint_path = load_best_checkpoint_if_available(
        model, save_path, metric=metric, device=device
    )
    if checkpoint_path is not None:
        print(f"Loaded best {metric} checkpoint for test: {checkpoint_path}")
    else:
        print(fallback_message)

    test_result, test_preds, test_targets = evaluate(
        model,
        test_loader,
        device,
        num_classes=len(test_dataset.activity_to_idx),
    )
    test_metrics = test_result["eval_metrics"]
    return {
        "checkpoint_metric": metric,
        "checkpoint_path": checkpoint_path,
        "metrics": {k: float(v) for k, v in test_metrics.items()},
        "predictions": [test_dataset.idx_to_activity[i] for i in test_preds],
        "targets": [test_dataset.idx_to_activity[i] for i in test_targets],
    }


def set_nested(config, path, value):
    keys = path.split(".")
    current = config
    for key in keys[:-1]:
        if key not in current or not isinstance(current[key], dict):
            current[key] = {}
        current = current[key]
    current[keys[-1]] = value


def apply_fixed_overrides(config, overrides):
    for override in overrides:
        set_nested(config, override["path"], override["value"])


def sample_param(trial, spec):
    spec_type = spec["type"]
    name = spec["name"]

    if spec_type == "float":
        kwargs = {"log": spec.get("log", False)}
        if "step" in spec:
            kwargs["step"] = spec["step"]
        return trial.suggest_float(name, spec["low"], spec["high"], **kwargs)

    if spec_type == "int":
        kwargs = {
            "step": spec.get("step", 1),
            "log": spec.get("log", False),
        }
        return trial.suggest_int(name, spec["low"], spec["high"], **kwargs)

    if spec_type == "categorical":
        return trial.suggest_categorical(name, spec["choices"])

    raise ValueError(f"Unsupported search-space type: {spec_type}")


def build_sampler(sampler_cfg):
    optuna = require_optuna()
    sampler_cfg = sampler_cfg or DEFAULT_STUDY_CONFIG["sampler"]
    sampler_name = sampler_cfg.get("name", "TPESampler")
    sampler_kwargs = {k: v for k, v in sampler_cfg.items() if k != "name"}

    sampler_cls = getattr(optuna.samplers, sampler_name, None)
    if sampler_cls is None:
        raise ValueError(f"Unsupported Optuna sampler: {sampler_name}")
    return sampler_cls(**sampler_kwargs)


def build_pruner(pruner_cfg):
    optuna = require_optuna()
    pruner_cfg = pruner_cfg or DEFAULT_STUDY_CONFIG["pruner"]
    pruner_name = pruner_cfg.get("name", "MedianPruner")
    pruner_kwargs = {k: v for k, v in pruner_cfg.items() if k != "name"}

    pruner_cls = getattr(optuna.pruners, pruner_name, None)
    if pruner_cls is None:
        raise ValueError(f"Unsupported Optuna pruner: {pruner_name}")
    return pruner_cls(**pruner_kwargs)


def build_study(optuna_config):
    optuna = require_optuna()
    study_cfg = {**DEFAULT_STUDY_CONFIG, **optuna_config.get("study", {})}
    storage = study_cfg["storage"]
    if storage.startswith("sqlite:///"):
        db_path = storage.replace("sqlite:///", "", 1)
        if db_path and db_path != ":memory:":
            os.makedirs(os.path.dirname(os.path.abspath(db_path)), exist_ok=True)
    return optuna.create_study(
        study_name=study_cfg["study_name"],
        direction=study_cfg["direction"],
        storage=storage,
        load_if_exists=study_cfg.get("load_if_exists", True),
        sampler=build_sampler(study_cfg.get("sampler")),
        pruner=build_pruner(study_cfg.get("pruner")),
    )

def train_one_run(config, trial=None, run_test=True, objective_metric="top5"):
    mlp_cfg = config["mlp"]
    lstm_cfg = config.get("lstm", {})
    action_graph_cfg = mlp_cfg["action_graph_embedder"]
    projector_cfg = mlp_cfg["projector"]
    attention_pool_cfg = mlp_cfg["attention_pooler"]
    head_cfg = mlp_cfg.get("head", {})

    experiment_name = config["experiment_name"]
    print(f"Running experiment: {experiment_name}")

    device = config["device"]
    if device == "cuda" and not torch.cuda.is_available():
        device = "cpu"

    num_epochs = config["training"]["num_epochs"]
    optimizer_name = config["training"]["optimizer"]
    learning_rate = config["training"]["learning_rate"]
    weight_decay = config["training"]["weight_decay"]
    scheduler_factor = config["training"]["scheduler_factor"]

    batch_size = config["data"]["batch_size"]
    num_workers = config["data"]["num_workers"]
    pin_memory = config["data"]["pin_memory"]

    fc_layers_num = mlp_cfg["fc_layers_num"]
    num_graphs = mlp_cfg["num_graphs"]

    use_pool = mlp_cfg["use_pool"]
    use_proj = mlp_cfg["use_proj"]

    graph_emb_dim = projector_cfg["graph_emb_dim"]
    layer_norm = projector_cfg.get("layer_norm", True)
    gelu = projector_cfg.get("gelu", True)
    head_dropout = head_cfg.get("dropout", 0.5)
    head_activation = head_cfg.get("activation", "gelu")

    graph_pool_interim_feat = attention_pool_cfg["graph_pool_interim_feat"]
    final_graph_emb_dim = attention_pool_cfg["final_graph_emb_dim"]
    hidden_size = lstm_cfg.get("hidden_size", final_graph_emb_dim)
    lstm_num_layers = lstm_cfg.get("num_layers", 2)
    lstm_bias = lstm_cfg.get("bias", True)
    lstm_bidirectional = lstm_cfg.get("bidirectional", False)
    recurrent_dropout = lstm_cfg.get("recurrent_dropout", 0.0)
    temporal_readout = lstm_cfg.get("readout")

    data_path = config["data"]["input_path"]
    metadata_root = config["data"]["metadata_root"]
    train_actions_csv = config["data"]["train_actions_csv"]
    val_actions_csv = config["data"]["val_actions_csv"]
    test_actions_csv = config["data"]["test_actions_csv"]
    easg_cache_path = config["data"].get("easg_cache_path")

    (
        train_samples,
        val_samples,
        test_samples,
        activity_to_idx,
        split_stats,
    ) = return_meccano_train_val_test_samples(
        dataset_root=data_path,
        train_actions_csv=train_actions_csv,
        val_actions_csv=val_actions_csv,
        test_actions_csv=test_actions_csv,
        num_graphs=num_graphs,
    )

    global_metadata_root = resolve_meccano_global_root(metadata_root)
    train_metadata_root = resolve_meccano_split_root(metadata_root, "Train")
    vocab_root = global_metadata_root or train_metadata_root

    if global_metadata_root is not None:
        verbs_path = os.path.join(vocab_root, "global_verbs.json")
        objs_path = os.path.join(vocab_root, "global_objects.json")
        rels_path = os.path.join(vocab_root, "global_relationships.json")
        attrs_path = os.path.join(vocab_root, "global_attributes.json")
    else:
        verbs_path = os.path.join(vocab_root, "verbs.json")
        objs_path = os.path.join(vocab_root, "objects.json")
        rels_path = os.path.join(vocab_root, "relationships.json")
        attrs_path = os.path.join(vocab_root, "attributes.json")

    with open(verbs_path, "r") as f:
        verbs = json.load(f)

    with open(objs_path, "r") as f:
        objs = json.load(f)

    with open(rels_path, "r") as f:
        rels = json.load(f)

    with open(attrs_path, "r") as f:
        attrs = json.load(f)

    graph_type = config["data"].get("graph_type", "full")

    if graph_type == "pruned":
        pruned_rels = {
            rel_name: rel_idx
            for rel_name, rel_idx in rels.items()
            if rel_name not in {"aux_direct_object", "aux_verb"}
        }
        if "gazed_at" not in pruned_rels:
            pruned_rels["gazed_at"] = max(pruned_rels.values(), default=-1) + 1
        num_rels = max(pruned_rels.values(), default=-1) + 1
    else:
        num_rels = len(rels)

    print(f"activity_to_idx : {activity_to_idx}")
    print(f"len(train_samples) : {len(train_samples)}")
    print(f"len(val_samples) : {len(val_samples)}")
    print(f"len(test_samples) : {len(test_samples)}")
    print(f"Graph type : {graph_type}")
    print(f"Vocabulary root : {vocab_root}")
    print(f"EASG cache path : {easg_cache_path}")
    print(f"MECCANO split stats : {json.dumps(split_stats, indent=2)}")

    train_dataset = GraphDatasetMeccano(
        metadata_root,
        "Train",
        train_samples,
        activity_to_idx,
        graph_type,
        easg_cache_path=easg_cache_path,
    )
    validation_dataset = GraphDatasetMeccano(
        metadata_root,
        "Val",
        val_samples,
        activity_to_idx,
        graph_type,
        easg_cache_path=easg_cache_path,
    )
    test_dataset = GraphDatasetMeccano(
        metadata_root,
        "Test",
        test_samples,
        activity_to_idx,
        graph_type,
        easg_cache_path=easg_cache_path,
    )

    assert train_dataset.activity_to_idx == validation_dataset.activity_to_idx
    assert train_dataset.activity_to_idx == test_dataset.activity_to_idx
    cls_mapping = train_dataset.activity_to_idx

    sampler_cfg = config["training"].get("sampler", {"name": "none"})
    train_sampler = build_train_sampler(train_dataset, activity_to_idx, sampler_cfg)
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=train_sampler is None,
        sampler=train_sampler,
        num_workers=num_workers,
        pin_memory=pin_memory,
        collate_fn=feature_collate_fn,
    )
    val_loader = DataLoader(
        validation_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        pin_memory=False,
        collate_fn=feature_collate_fn,
    )
    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=0,
        pin_memory=False,
        collate_fn=feature_collate_fn,
    )

    model = GraphLSTM(
        num_graphs=num_graphs,
        num_verbs=len(verbs),
        num_objects=len(objs),
        num_rels=num_rels,
        num_attrs=len(attrs),
        n_classes=len(cls_mapping),
        fc_layers_num=fc_layers_num,
        graph_emb_dim=graph_emb_dim,
        final_graph_emb_dim=final_graph_emb_dim,
        graph_pool_interim_feat=graph_pool_interim_feat,
        layer_norm=layer_norm,
        gelu=gelu,
        head_dropout=head_dropout,
        head_activation=head_activation,
        device=device,
        action_graph_kwargs=action_graph_cfg,
        use_pool=use_pool,
        use_proj=use_proj,
        hidden_size=hidden_size,
        num_layers=lstm_num_layers,
        bias=lstm_bias,
        bidirectional=lstm_bidirectional,
        recurrent_dropout=recurrent_dropout,
        temporal_readout=temporal_readout,
    ).to(device)

    class_weights = None
    if config["training"]["loss"]["ifw"]:
        class_weight_alpha = float(
            config["training"]["loss"].get("class_weight_alpha", 0.5)
        )
        class_weights = compute_class_weights(
            train_dataset, activity_to_idx, alpha=class_weight_alpha
        )
        print(class_weights)
    if optimizer_name == "adam":
        opt = torch.optim.Adam(
            params=model.parameters(),
            lr=learning_rate,
            weight_decay=weight_decay,
        )
    elif optimizer_name == "sgd":
        opt = torch.optim.SGD(
            params=model.parameters(),
            lr=learning_rate,
            momentum=0.9,
            weight_decay=weight_decay,
        )
    else:
        raise ValueError(f"Unsupported optimizer: {optimizer_name}")

    scheduler = None
    if scheduler_factor != 1.0:
        scheduler = torch.optim.lr_scheduler.MultiplicativeLR(
            opt, lr_lambda=lambda epoch: scheduler_factor
        )

    save_path = os.path.join(
        config["output"]["base_path"],
        config["experiment_name"],
        (
            f"dino_model_fc_layer_{fc_layers_num}_num_epoch_{num_epochs}"
            f"_graph_emb_dim_{graph_emb_dim}_lstm_hidden_{hidden_size}"
            f"_final_graph_emb_dim_{final_graph_emb_dim}"
            f"_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        ),
    )
    os.makedirs(save_path, exist_ok=True)

    results = {}
    best_epoch_result = {"top1": -1, "top5": -1, "f1": -1}
    best_objective_value = float("-inf")
    global_step = 0

    experiment_config = {
        "experiment_name": experiment_name,
        "fc_layers_num": fc_layers_num,
        "num_epochs": num_epochs,
        "batch_size": batch_size,
        "learning_rate": learning_rate,
        "weight_decay": weight_decay,
        "optimizer": optimizer_name,
        "scheduler_factor": scheduler_factor,
        "num_classes": len(cls_mapping),
        "device": device,
        "mlp": config["mlp"],
        "lstm": config.get("lstm", {}),
        "data": config["data"],
        "sampler": sampler_cfg,
        "loss": config["training"]["loss"],
        "split_stats": split_stats,
    }

    initial_checkpoint_path = config["training"].get("initial_checkpoint_path")
    eval_initial_checkpoint = config["training"].get("eval_initial_checkpoint", False)
    if initial_checkpoint_path:
        experiment_config["initial_checkpoint_path"] = initial_checkpoint_path
        checkpoint = torch.load(
            initial_checkpoint_path, map_location=device, weights_only=False
        )
        model.load_state_dict(checkpoint["model_state_dict"])
        if config["training"].get("resume_optimizer", False):
            opt.load_state_dict(checkpoint["optimizer_state_dict"])
        print(f"Loaded initial checkpoint: {initial_checkpoint_path}")

    with open(os.path.join(save_path, "experiment_config.json"), "w") as f:
        json.dump(experiment_config, f, indent=2)

    with open(os.path.join(save_path, "class_mapping.json"), "w") as f:
        json.dump(cls_mapping, f, indent=2)

    if trial is not None:
        trial_metadata = {
            "trial_number": trial.number,
            "params": trial.params,
            "objective_metric": objective_metric,
        }
        with open(os.path.join(save_path, "optuna_trial.json"), "w") as f:
            json.dump(trial_metadata, f, indent=2)

    if initial_checkpoint_path and eval_initial_checkpoint:
        initial_test_result, initial_test_preds, initial_test_targets = evaluate(
            model,
            test_loader,
            device,
            num_classes=len(test_dataset.activity_to_idx),
        )
        initial_test_metrics = initial_test_result["eval_metrics"]
        initial_test_summary = {
            "checkpoint_path": initial_checkpoint_path,
            "metrics": {k: float(v) for k, v in initial_test_metrics.items()},
            "predictions": [
                test_dataset.idx_to_activity[i] for i in initial_test_preds
            ],
            "targets": [test_dataset.idx_to_activity[i] for i in initial_test_targets],
        }

        with open(os.path.join(save_path, "initial_test_results.json"), "w") as f:
            json.dump(initial_test_summary, f, indent=2)

        print(
            "Initial checkpoint test metrics: "
            f"Top-1 {initial_test_metrics['top1']*100:.2f}% | "
            f"Top-5 {initial_test_metrics['top5']*100:.2f}% | "
            f"Avg. Prec. {initial_test_metrics['avg_precision']*100:.2f}% | "
            f"Avg. Recall {initial_test_metrics['avg_recall']*100:.2f}% | "
            f"Avg. F1 {initial_test_metrics['avg_f1']*100:.2f}%"
        )

    model.train()
    epoch_preds = {k: {} for k in range(num_epochs)}

    for epoch in tqdm(
        range(num_epochs),
        desc=f"Training for {num_epochs} epochs",
        unit="epoch",
        total=num_epochs,
    ):
        print(f"Epoch {epoch+1}/{num_epochs}\n")
        loss_func = build_loss_fn(
            config["training"]["loss"],
            class_weights,
            epoch=epoch,
            num_epochs=num_epochs,
        )

        epoch_result, global_step, preds, targets = do_epoch(
            device=device,
            net=model,
            opt=opt,
            train_loader=train_loader,
            validate_loader=val_loader,
            global_step=global_step,
            num_classes_train=len(cls_mapping),
            num_classes_val=len(validation_dataset.activity_to_idx),
            loss_func=loss_func,
        )

        epoch_preds[epoch]["predictions"] = [
            train_dataset.idx_to_activity[i] for i in preds
        ]
        epoch_preds[epoch]["targets"] = [
            train_dataset.idx_to_activity[i] for i in targets
        ]

        val_metrics = epoch_result["val"]["eval_metrics"]

        print(
            "\nValidation metrics: "
            f"Top-1 {val_metrics['top1']*100:.2f}% | "
            f"Top-5 {val_metrics['top5']*100:.2f}% | "
            f"Avg. Prec. {val_metrics['avg_precision']*100:.2f}% | "
            f"Avg. Recall {val_metrics['avg_recall']*100:.2f}% | "
            f"Avg. F1 {val_metrics['avg_f1']*100:.2f}%"
        )

        if val_metrics["top1"] > best_epoch_result["top1"]:
            best_epoch_result["top1"] = val_metrics["top1"]
            store_model(
                net=model, opt=opt, epoch=epoch, save_path=save_path, metric="acc"
            )
            store_model(
                net=model, opt=opt, epoch=epoch, save_path=save_path, metric="top1"
            )
            print(f"New best Top-1 accuracy model saved: {val_metrics['top1']*100:.2f}%")

        if val_metrics["top5"] > best_epoch_result["top5"]:
            best_epoch_result["top5"] = val_metrics["top5"]
            store_model(
                net=model, opt=opt, epoch=epoch, save_path=save_path, metric="top5"
            )
            print(f"New best Top-5 accuracy model saved: {val_metrics['top5']*100:.2f}%")

        if val_metrics["f1"] > best_epoch_result["f1"]:
            best_epoch_result["f1"] = val_metrics["f1"]
            store_model(
                net=model, opt=opt, epoch=epoch, save_path=save_path, metric="f1"
            )
            print(f"New best F1 model saved: {val_metrics['f1']*100:.2f}%")

        objective_value = val_metrics[objective_metric]
        best_objective_value = max(best_objective_value, objective_value)

        if trial is not None:
            trial.report(objective_value, step=epoch)
            if trial.should_prune():
                optuna = require_optuna()
                raise optuna.TrialPruned(
                    f"Trial pruned at epoch {epoch} with {objective_metric}={objective_value:.6f}"
                )

        results[epoch] = epoch_result

        if scheduler is not None:
            scheduler.step()

        print(f"Epoch {epoch+1} completed")

    print(f"Best validation Top-1 accuracy: {best_epoch_result['top1']*100:.2f}%")
    print(f"Best validation Top-5 accuracy: {best_epoch_result['top5']*100:.2f}%")
    print(f"Best validation F1: {best_epoch_result['f1']*100:.2f}%")

    if run_test:
        top1_test_summary = evaluate_checkpoint(
            model,
            save_path,
            "top1",
            test_loader,
            test_dataset,
            device,
            "No best top1 checkpoint found; using final epoch model for top1 test.",
        )
        top5_test_summary = evaluate_checkpoint(
            model,
            save_path,
            "top5",
            test_loader,
            test_dataset,
            device,
            "No best top5 checkpoint found; using current model for top5 test.",
        )

        with open(os.path.join(save_path, "final_test_results_top1.json"), "w") as f:
            json.dump(top1_test_summary, f, indent=2)

        with open(os.path.join(save_path, "final_test_results_top5.json"), "w") as f:
            json.dump(top5_test_summary, f, indent=2)

        with open(os.path.join(save_path, "final_test_results.json"), "w") as f:
            json.dump(top1_test_summary, f, indent=2)

        print(
            "Best Top-1 checkpoint test metrics: "
            f"Top-1 {top1_test_summary['metrics']['top1']*100:.2f}% | "
            f"Top-5 {top1_test_summary['metrics']['top5']*100:.2f}% | "
            f"Avg. Prec. {top1_test_summary['metrics']['avg_precision']*100:.2f}% | "
            f"Avg. Recall {top1_test_summary['metrics']['avg_recall']*100:.2f}% | "
            f"Avg. F1 {top1_test_summary['metrics']['avg_f1']*100:.2f}%"
        )
        print(
            "Best Top-5 checkpoint test metrics: "
            f"Top-1 {top5_test_summary['metrics']['top1']*100:.2f}% | "
            f"Top-5 {top5_test_summary['metrics']['top5']*100:.2f}% | "
            f"Avg. Prec. {top5_test_summary['metrics']['avg_precision']*100:.2f}% | "
            f"Avg. Recall {top5_test_summary['metrics']['avg_recall']*100:.2f}% | "
            f"Avg. F1 {top5_test_summary['metrics']['avg_f1']*100:.2f}%"
        )

    return best_objective_value

def objective(trial, base_config, optuna_config):
    config = copy.deepcopy(base_config)
    objective_cfg = {**DEFAULT_OBJECTIVE_CONFIG, **optuna_config.get("objective", {})}
    apply_fixed_overrides(config, optuna_config.get("fixed_overrides", []))

    for spec in optuna_config.get("search_space", []):
        value = sample_param(trial, spec)
        set_nested(config, spec["path"], value)

    return train_one_run(
        config,
        trial=trial,
        run_test=objective_cfg.get("run_test", False),
        objective_metric=objective_cfg.get("metric", "top5"),
    )

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--optuna-config-path", type=str
    )
    parser.add_argument(
        "--config-path", type=str
    )
    args = parser.parse_args()
    optuna_config_path = args.optuna_config_path
    config_path = args.config_path

    with open(optuna_config_path, "r") as f:
        optuna_config = json.load(f)

    with open(config_path, "r") as f:
        config = json.load(f)

    study = build_study(optuna_config)
    study_cfg = {**DEFAULT_STUDY_CONFIG, **optuna_config.get("study", {})}

    study.optimize(
        lambda trial: objective(trial, config, optuna_config),
        n_trials=study_cfg["n_trials"],
    )
    print(study.best_trial.number)
    print(study.best_trial.value)
    print(study.best_trial.params)
